### PR TITLE
Reviews

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
A mixed set of code reviews

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks for your work!
For me it would be interesting to add the php-cs-fixer configuration you used to the project as well. That way we may prevent future style issues. Or if it's just a single command you ran, would you add it to the README file?

**Comment by EmanueleMinotto** [comment]
I used different tools for this PR, anyway added the closest php-cs-fixer configuration, let me know if this is good.

PS: I've created a CONTRIBUTING.md file because integrated with GitHub, should I add the content to the README.md too?

**Comment by matthiasnoback** [comment]
Thanks man, is the configuration sufficient? It seems that only the sort uses fix will be used?

**Comment by EmanueleMinotto** [comment]
> By default, all PSR-2 fixers and some additional ones are run. The "contrib level" fixers cannot be enabled via this option; you should instead set them manually by their name via the --fixers option.

https://github.com/EmanueleMinotto/symfony-console-form/commit/3e91406d4170b11ad2e9d8b85c52beb36cd60b0e was realized using that configuration, so I guess PSR2 checks are included by default.

**Comment by matthiasnoback** [comment]
Aha, but you had already fixed everything, right? ;) Anyway, I believe you of course! Let's merge this.

**Pull request merged**
