### PR TITLE
Added ~4.0 version to Symfony components.

### LINKED ISSUE #25: Support for Symfony 4
Today Symfony 4.0.0 was released and currently this library just supports ```"~2.8|~3.0"``` symfony versions.

### PR DESCRIPTION
**Pull request by tarlepp**
Fixes #25

### CODE REVIEW

**Comment by tarlepp** [comment]
@matthiasnoback Any info if/when you're going to merge this one and bump version ?

**Comment by matthiasnoback** [comment]
Thanks for submitting this PR. Could you take a look at the `.travis.yml` file as well, to make sure we also test against 4.0? Allowing 4.0 is one thing, but I'm not sure everything will still work :)

**Comment by matthiasnoback** [comment]
Hey @tarlepp I'm looking at some of the issues. It may be a bit more work, since 4.0 changed some things about forms apparently ;) But I'll take another stab it. You can find my work based on your work in the branch `tarlepp-master`.

**Comment by matthiasnoback** [comment]
There's one issue that needs to be fixed: Symfony 2.8 requires the use of `choices_as_values` option to make it work. This option is removed in 4.0. I think I'll just drop support for 2.8.

**Comment by matthiasnoback** [comment]
It's done, thanks again. `v2.4.0` is available now :)

**Comment by tarlepp** [comment]
@matthiasnoback and thanks to you too for quick response for this!

**Comment by matthiasnoback** [comment]
Sure thing, by the way, what are you using this library for?

**Comment by tarlepp** [comment]
on several console commands for eg. user and api key management, feel free to take closer look there https://github.com/tarlepp/symfony-flex-backend/tree/master/src/Command/User and https://github.com/tarlepp/symfony-flex-backend/tree/master/src/Command/ApiKey

So basically just some utils to help system administrators to manage users and apikeys

**Comment by matthiasnoback** [comment]
Okay, sounds like the ideal use case in fact :) Thanks!

**Comment by tarlepp** [comment]
yeah, you could test those with that repo if you like

**Pull request merged**
