### PR TITLE
Symfony 7 support

### LINKED ISSUE #66: Support for Symfony 7
Symfony 7 was released a while a back, so I think that we should create new version of this awesome library for Symfony 7.

### PR DESCRIPTION
**Pull request by tarlepp**
~~I'm not familiar with Behat tests so could someone give some help to solve that issue?~~

Fixed this Behat issue, just needed to convert some `@Assert` docblocks to attributes.

Another thing that I found is [InteractiveFormContainerAwareCommand](https://github.com/matthiasnoback/symfony-console-form/blob/03a0e9d725db5cc0696b276ed465ce6bd1e8c2db/src/Console/Command/InteractiveFormContainerAwareCommand.php#L8) which is using `Symfony\Component\DependencyInjection\ContainerAwareTrait;` and that is deprecated.

Although didn't find any references to this abstract class on code or documentation, should we just remove that trait from that abstract class or what?

Fixed #66

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Cool!

> Another thing that I found is [InteractiveFormContainerAwareCommand](https://github.com/matthiasnoback/symfony-console-form/blob/03a0e9d725db5cc0696b276ed465ce6bd1e8c2db/src/Console/Command/InteractiveFormContainerAwareCommand.php#L8) which is using Symfony\Component\DependencyInjection\ContainerAwareTrait; and that is deprecated.

Sounds okay to remove this one.

**Comment by tarlepp** [comment]
> Cool!
> 
> > Another thing that I found is [InteractiveFormContainerAwareCommand](https://github.com/matthiasnoback/symfony-console-form/blob/03a0e9d725db5cc0696b276ed465ce6bd1e8c2db/src/Console/Command/InteractiveFormContainerAwareCommand.php#L8) which is using Symfony\Component\DependencyInjection\ContainerAwareTrait; and that is deprecated.
> 
> Sounds okay to remove this one.

Or should we marked that as deprecated first and in next major version remove that?

**Comment by matthiasnoback** [comment]
I think we can get rid of it and release the next major version for this package. The documented way (in the README file) is the best way to use this tool I think.

**Comment by tarlepp** [comment]
> I think we can get rid of it and release the next major version for this package. The documented way (in the README file) is the best way to use this tool I think.

Roger, will do that later today.

**Comment by matthiasnoback** [comment]
Thanks, released as v6.0.0 https://github.com/matthiasnoback/symfony-console-form/releases/tag/v6.0.0

**Pull request merged**
