### PR TITLE
allow symfony 5

### PR DESCRIPTION
**Pull request by Jeroeny**
#SymfonyHackday

### CODE REVIEW

**Comment by matthiasnoback** [comment]
@Jeroeny I appreciate it, but the build fails; would you like to dive and fix?

**Comment by Jeroeny** [comment]
Yes, I'll look into it and see how far I get.

**Comment by tarlepp** [comment]
any updates with this?

**Comment by tarlepp** [comment]
I did some quick tests with this, and it seems like tests are failing on current master branch also.

And the reason for that is that console output doesn't match with the test case, there seems to be some extra characters on console output versus test case.

Console output
```
Select color [red]:
[red   ] Red
[blue  ] Blue
[yellow] Yellow
> b[K7lue8l[K7ue8u[K7e8e[K78
Array
(
[color] => blue
)
```

And test assumes that output is:
```
Select color [red]:
[red   ] Red
[blue  ] Blue
[yellow] Yellow
> blue
Array
(
[color] => blue
)
```

I hope this helps with PR or someone could make new PR to fix this to master before this PR.

**Comment by Jeroeny** [comment]
Indeed, haven't been able to find the cause for that console output yet. 

I've added Symfony 5 to the travis CI, but to be able to run the tests behat needs to support Symfony 5 first.

**Comment by matthiasnoback** [comment]
Thanks for looking into this!
I have no clue myself, and haven't used Symfony 5. The only thing I can think of is that maybe Symfony now produces unicode output or something (if it didn't before, I honestly don't know)?

**Comment by tarlepp** [comment]
> Thanks for looking into this!
> I have no clue myself, and haven't used Symfony 5. The only thing I can think of is that maybe Symfony now produces unicode output or something (if it didn't before, I honestly don't know)?

note that this same error is happening with current master branch too.

**Comment by matthiasnoback** [comment]
Ah, okay, I didn't get that. To be honest, I won't have time to work on this any time soon, so if anyone wants to pick it up, please do.

**Comment by tarlepp** [comment]
Is there any updates for this?

**Comment by matthiasnoback** [comment]
Okay, it seems that in the meantime the issue with the console output simply disappeared. I have been updating the test suite to deal with any other differences in output, and some other things that no longer work or work differently in Symfony 5. I'm close to making everything work for Symfony 5, so the next version of this library will only support Symfony 5. This should save me some trouble in the future ;) I'm not using this library anywhere, so I'll have to rely on feedback from actual users. But at least, I'm happy that we have a solution now.

**Pull request merged**
