### PR TITLE
add support for integer fields

### PR DESCRIPTION
**Pull request by Guite**
This PR adds a transformer for integer form fields.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Ah, actually, I've just changed the hierarchy a bit. You now have to extend from `AbstractTextInputBasedTransformer` ;) Could you also add an example to the `interactive.feature` file to show that it works?

**Comment by Guite** [comment]
> You now have to extend from AbstractTextInputBasedTransformer ;)

Done.

> Could you also add an example to the interactive.feature file to show that it works?

Sorry, I am not used to this.
Is there an example for number fields which I can use as foundation?

**Comment by matthiasnoback** [comment]
You could create a new form type and copy an existing example to use that form. If it's too much trouble I can do it too.

**Comment by Guite** [comment]
> If it's too much trouble I can do it too.

That would be awesome. Please do so.

**Pull request merged**
