### PR TITLE
Add PhpStan and implement suggested fixes

### PR DESCRIPTION
**Pull request by rpkamp**
There is one error that is not easy to fix regarding the `NonInteractiveRootInteractor` that calls `setOption` on `InputInterface` with an array, which is not allowed. But to fix this the entire structure of how FormInteractors work need to be reviewed. Is this something you would be interested in?

Also, this is a breaking change as it changes the signature of the Transformers, so if anyone has extended those it will break for them.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks man! I was sick last week - will take a closer look later! Didn't ever use PhpStan before by the way, seems like a useful thing to start doing ;)

**Comment by matthiasnoback** [comment]
Interesting question about `setOption()`. It's just very unfortunate that `$value` is typed like that, because the actual value in the internal `$options` attribute of `Input` *can* be an array (otherwise this code wouldn't even work of course). I'd expect something like `addOption()` to exist, but it doesn't. Not sure if this is worth the effort to fix anyway.

So now I'm curious, are you actually using this library?

**Comment by matthiasnoback** [comment]
Wait, I didn't check, but this doesn't really add PhpStan ;) Would you still like to do that?

**Comment by rpkamp** [comment]
I can't add PhpStan at this point because it requires symfony/console:^3.2 so the Travis build for symfony 3.0 breaks. I could add the PHAR but that's quite large so I'm not sure if that's something you'd want.

Regarding the input, what I was thinking is that if all Transformers always return an array of data then the whole problem would go away, and it would make for a more consistent internal API. But I'm not sure if this easy to achieve. I might have a stab at it later.

I'm planning to use this library to test a form with a lot of fields so I can pre-fill them on development on the command line, which also allows me to see nice debugging information from the API calls resulting from executing the command the form is filling :smiley:

**Comment by matthiasnoback** [comment]
Okay, I would not be opposed to increasing some dependency version requirements.

I have no idea about your suggestion. It's been a long time since I've been actively working on this library anyway. I still think it's a useful thing and it's living proof that the form component is quite well designed (decoupled from the web and all). It's also nice to know that it's helpful to you.

**Pull request merged**
